routes:
  /:
    template: home
    data: page.home
  /about/:
    template: about
    data: page.about

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
