routes:
  /:
    template: home
    data: page.home
  /about/:
    template: about
    data: page.about

collections:
  /posts/:
    permalink: /posts/{slug}/
    template: index
    filter: tag:-hash-university+tag:-hash-nhs-trust+tag:-hash-industry

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
