routes:
  /:
    template: home
    data: page.home
  /about/:
    template: about
    data: page.about
  /people/:
    template: people
    data: page.people

collections:
  /university/:
    permalink: /university/{slug}/
    filter: tag:hash-university
  /nhs-trust/:
    permalink: /nhs-trust/{slug}/
    filter: tag:hash-nhs-trust
  /industry/:
    permalink: /industry/{slug}/
    filter: tag:hash-industry
  /people/:
    permalink: /people/{slug}/
    template: person
    filter: tag:person
  /opportunities/:
    permalink: /opportunities/{slug}/
    template: opportunity
    filter: tag:opportunity
    data: tag.opportunity
  /posts/:
    permalink: /posts/{slug}/
    template: index
    filter: tag:news

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
