apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openlab-hosting

resources:
  - env-secret.yml
  - ingress.yml
  - service.yml
  - statefulset.yml
  - volume.yml

configMapGenerator:
  - name: northfutures-resources
    files:
      - config.json
